apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bcuwsprhh-go 
  janus-idp.io/tekton: bcuwsprhh-go
  backstage.io/kubernetes-id: bcuwsprhh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bcuwsprhh-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  