apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bcuwsprhh-go-gitops
  description: This is GitOps manifest for bcuwsprhh-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: bcuwsprhh-go
    backstage.io/kubernetes-id: bcuwsprhh-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bcuwsprhh-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bcuwsprhh-go
